<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: yii.php 1394 2009-09-06 01:04:11Z qiang.xue $
*/
/**
 * @link http://www.yiiframework.com/doc/cookbook/18/
 */
$messages = array (
  '{attribute} cannot be blank.' => 'El campo <span class="invalid-attribute">{attribute}</span> no puede estar vacío.',
);
return CMap::mergeArray( require(Yii::getFrameworkPath().'/messages/es/yii.php'), $messages);
